import { listCapabilities } from '@telyad/ad-formats';
import type { AdCapability, MediaPlan, MediaPlanItem, MediaPlanRequest } from '@telyad/types';
import { isNetworkLive } from '@telyad/types';
import { unit } from './seed-random';

/** Recommends a media plan across the capability universe. Swappable for real AI. */
export interface AIPlanner {
  recommendMediaPlan(request: MediaPlanRequest): MediaPlan;
}

const BASE_POOL = 80_000_000; // MTN demo subscriber base
const IMPRESSION_COST_MAJOR = 0.12; // ~₦120 CPM, demonstration blended rate

/** Indefinite article agreeing with the following word (e.g. "an Acquisition"). */
function article(word: string): 'a' | 'an' {
  return /^[aeiou]/i.test(word.trim()) ? 'an' : 'a';
}

function score(cap: AdCapability, req: MediaPlanRequest): number {
  let s = 1;
  const obj = req.objective.toLowerCase();
  if (cap.objectives.some((o) => o.toLowerCase() === obj)) s += 3;
  if (cap.mechanics.some((m) => obj.includes(m) || m.includes(obj.split(' ')[0] ?? ''))) s += 1;
  if (cap.recommendedSectors.some((sec) => sec.toLowerCase() === req.sector.toLowerCase())) s += 3;
  if (req.deviceMix === 'both' || cap.deviceClass === 'both' || cap.deviceClass === req.deviceMix) s += 1;
  if (isNetworkLive(cap.defaultNetworkStatus)) s += 2; // prefer network-ready
  s += unit(`${cap.id}:${req.sector}:${req.objective}`) * 0.9; // stable tie-break
  return s;
}

export class DemoAIPlanner implements AIPlanner {
  recommendMediaPlan(request: MediaPlanRequest): MediaPlan {
    const candidates = listCapabilities()
      .filter((c) => c.telyadStatus !== 'DISABLED' && c.defaultNetworkStatus !== 'DISABLED')
      .map((c) => ({ c, s: score(c, request) }))
      .sort((a, b) => b.s - a.s);

    // Greedy pick with family diversity, target 5 items.
    const picked: { c: AdCapability; s: number }[] = [];
    const familiesUsed = new Set<string>();
    for (const cand of candidates) {
      if (picked.length >= 5) break;
      if (familiesUsed.has(cand.c.family) && picked.length < 4) continue;
      picked.push(cand);
      familiesUsed.add(cand.c.family);
    }
    if (picked.length < 5) {
      for (const cand of candidates) {
        if (picked.length >= 5) break;
        if (!picked.includes(cand)) picked.push(cand);
      }
    }

    const totalScore = picked.reduce((a, p) => a + p.s, 0);
    const budgetMajor = request.budgetMinor / 100;
    const grossImpressions = Math.min(BASE_POOL * 2.5, budgetMajor / IMPRESSION_COST_MAJOR);

    const items: MediaPlanItem[] = picked.map(({ c, s }) => {
      const sharePct = Math.round((s / totalScore) * 100);
      const estimatedReach = Math.round(((grossImpressions * sharePct) / 100) * 0.68);
      return {
        capabilityId: c.id,
        capabilityName: c.name,
        family: c.family,
        sharePct,
        budgetMinor: Math.round((request.budgetMinor * sharePct) / 100),
        reason: `For ${article(request.objective)} ${request.objective} objective in ${request.sector}: ${c.name} — ${c.bestUseCases[0] ?? c.description}`,
        estimatedReach: Math.min(BASE_POOL, estimatedReach),
        pricingModel: c.pricingModels[0]!,
        networkStatus: c.defaultNetworkStatus,
      };
    });

    // Normalise shares to sum ~100.
    const shareSum = items.reduce((a, i) => a + i.sharePct, 0);
    if (items.length && shareSum !== 100) items[0]!.sharePct += 100 - shareSum;

    const totalEstimatedReach = Math.min(
      BASE_POOL,
      Math.round(items.reduce((a, i) => a + i.estimatedReach, 0) * 0.82),
    );
    const networkWarnings = picked
      .filter((p) => !isNetworkLive(p.c.defaultNetworkStatus))
      .map(
        (p) =>
          `${p.c.name} is a TelyAd capability requiring network enablement on MTN before it can go live.`,
      );

    return {
      request,
      items,
      totalEstimatedReach,
      estimatedFrequency: Math.round((1.6 + unit(request.sector + request.objective) * 1.8) * 10) / 10,
      networkWarnings,
      notes:
        'Demonstration media plan generated by deterministic rules. Availability and delivery are subject to participating network capabilities, technical integration, regulatory requirements and network approval.',
      generatedBy: 'demonstration-rules',
    };
  }
}
